FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma/
RUN npm ci
RUN npx prisma generate

COPY src/lib ./src/lib
COPY src/types ./src/types
COPY src/app/api ./src/app/api
COPY tsconfig.json ./

CMD ["node", "-r", "ts-node/register", "src/lib/cron/index.ts"]
