FROM node:20-alpine
RUN apk add --no-cache openssl
WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma/
RUN npm ci --legacy-peer-deps
RUN npx prisma generate

COPY src/lib ./src/lib
COPY src/types ./src/types
COPY src/app/api ./src/app/api
COPY tsconfig.json ./

CMD ["npx", "tsx", "src/lib/cron/index.ts"]
